---
title: "Global Breastfeeding Collective"
---

```{r setup, include=FALSE}

setwd("C:/Users/crish/OneDrive/Documents/UNICEF/1. BAI/Tableau")

library(xlsx)
GBC <- read.xlsx("Scorecard maps R.xlsx", 1)

GBC$DonorFundingUSDPerLiveBir<- round(GBC$DonorFundingUSDPerLiveBir, 2)
GBC$NUMBabyfriendly<- round(GBC$NUMBabyfriendly,1) 
GBC$PrimaryHealthcareFacilities <- round(GBC$PrimaryHealthcareFacilities,1)
GBC$DistrictsImplementingCommuni<- round(GBC$DistrictsImplementingCommuni,1)
#GBC$breastfedwithinanhourofb <- round(breastfedwithinanhourofb,1)
#GBC$breastfedexclusivelyfor6m <- round(breastfedexclusivelyfor6m,1)
GBC$breastfedat1yearold <- round(GBC$breastfedat1yearold,1)
GBC$breastfedat2yrsold <- round(GBC$breastfedat2yrsold,1)

GBC_table <- subset(GBC, select=c(UNRegion, Country, DonorFundingUSDPerLiveBir, 
                                  labelCode, labelCompliance,NUMBabyfriendly, 
                                  PrimaryHealthcareFacilities, DistrictsImplementingCommuni,
                                  NUMWBTi, NUMExcBF, breastfedwithinanhourofb,
                                  breastfedexclusivelyfor6m,breastfedat1yearold,
                                  breastfedat2yrsold))
```


```{r, echo=FALSE}
library(DT)
GBCTable <- datatable(GBC_table, 
          colnames = c('Region', 'Country', 
                       'Amount of Donor Funding for Breastfeeding', 
                       'Status of Code Implementation in Legislation', 
                       'Status of Paid Maternity Leave',
                       'Status of Ten Steps to Succesful Breastfeeding',
                       '% Primary Healthcare Facilities Offering Individual IYCF Counselling',
                       '% Districts Offering Community Breastfeeding Programmes',
                       'Last Date of WBTi Assessment',
                       'Last Date of Exclusive Breastfeeding Report',
                       'Rates of Early Initiation at <1 hour',
                       'Rates of Exclusive Breastfeeding from 0-5 months',
                       'Rates of Continued Breastfeeding at 1 year old',
                       'Rates of Continued Breastfeeding at 2 years old'), 
          class = "display", width=100, rownames=NULL,
          filter = 'top', options = list(pageLength = 100, autoWidth = TRUE),
          caption = '')%>% 

  formatStyle('DonorFundingUSDPerLiveBir',
  color = styleInterval(c(-1, 1, 2, 5), c('#d4d4d0', '#cc3333', '#eb8c2e', '#f8c623', '#009f49' )))%>%

  formatStyle('labelCode',
  color = styleEqual(c('No data', 'No legal measures', 'Few provisions in law', 
                       'Many provisions in law', 'Full provisions in law'), 
                     c('#d4d4d0', '#cc3333', '#eb8c2e', '#f8c623', '#009f49' )))%>%

  formatStyle('labelCompliance',
  color = styleEqual(c('No data', 'Does not meet', 'Meets leave length only', 
                       'Meets basic provisions', 'Meets recommended provisions'), 
                     c('#d4d4d0', '#cc3333', '#eb8c2e', '#f8c623', '#009f49' )))%>%

  formatStyle('NUMBabyfriendly',
  color = styleInterval(c(0, 19.5, 49.5), c('#cc3333', '#eb8c2e', '#f8c623', '#009f49' )))%>%

  formatStyle('PrimaryHealthcareFacilities',
  color = styleInterval(c(24.5, 49.5, 74.5), c('#cc3333', '#eb8c2e', '#f8c623', '#009f49' )))%>%

  formatStyle('DistrictsImplementingCommuni',
  color = styleInterval(c(24.5, 49.5, 74.5), c('#cc3333', '#eb8c2e', '#f8c623', '#009f49' )))%>%

  formatStyle('NUMWBTi',
  color = styleInterval(c(0, 2006, 2011), c('#cc3333', '#eb8c2e', '#f8c623', '#009f49' )))%>%

  formatStyle('NUMExcBF',
  color = styleInterval(c(0, 2006, 2011), c('#cc3333', '#eb8c2e', '#f8c623', '#009f49' )))%>%

  formatStyle('breastfedwithinanhourofb',
  color = styleInterval(c(29.5, 49.5, 69.5), c('#cc3333', '#eb8c2e', '#f8c623', '#009f49' )))%>%

  formatStyle('breastfedexclusivelyfor6m',
  color = styleInterval(c(19.5, 39.5, 59.5), c('#cc3333', '#eb8c2e', '#f8c623', '#009f49' )))%>%

  formatStyle('breastfedat1yearold',
  color = styleInterval(c(39.5, 59.5, 79.5), c('#cc3333', '#eb8c2e', '#f8c623', '#009f49' )))%>%

  formatStyle('breastfedat2yrsold',
  color = styleInterval(c(39.5, 59.5, 79.5), c('#cc3333', '#eb8c2e', '#f8c623', '#009f49' )))

#DT:::DT2BSClass(c('compact','collapse', 'cell-border'))

GBCTable

```





